[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
new_dex = "9qUrso2c4cKTF6JPNb8V5GHXWHXmw3hinRM61imH8Fr2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
